import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@components/navbar/Navbar'
import Image from 'next/image'

const font = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      
      <body className={font.className}>
        <Navbar
          buttons={[{ title: 'Timeline', destination:"/profile",  icon: 'reel-svgrepo-com.svg'}, 
                    { title: 'Images' , destination:"/section-images", icon: 'gallery-send-svgrepo-com.svg'}, 
                    { title: 'Matterport' , destination:"Link", icon: 'monitor-camera-svgrepo-com.svg'}
                  ]}
          style={{position: 'sticky'}}
        />
        {children}
      </body>
    </html>
  )
}
