import './globals.css'
import { Alfa_Slab_One } from 'next/font/google'
import Navbar from '@components/navbar/Navbar'

const font = Alfa_Slab_One({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
