INSERT INTO "Section" (id, title, date, description, content, model, "arLink")
VALUES 
('1', 'Hannover wird gegründet!', '12.04.1896', 'Hannover 96 wurde 1896 als „Hannoversche Fußball-Club von 1896 (HFC)“ gegründet, begann jedoch erst 1899 mit Fußball und wurde 1901 ein reiner Fußballverein.', 'Fast 80.000 Zuschauer sind am 23. Mai 1954 ins Hamburger Volksparkstadion gekommen. Hannover 96 und der 1. FC Kaiserslautern stehen sich im Endspiel um die deutsche Fußball-Meisterschaft gegenüber. Die Norddeutschen sind gegen die Elf um Nationalmannschaftskapitän Fritz Walter krasser Außenseiter. Nach 90 Minuten steht es jedoch 5:1 für Hannover. Auch mehr als 50 Jahre später gilt der Erfolg als eine der größten Überraschungen in der deutschen Fußball-Geschichte.', 'Model_Google', 'https://ar.scanblue.com/av8tDy'),
('2', 'Entstehung Hannoversche Sportverein von 1896', '03.06.1913', NULL, 'Es entstand der Hannoversche Sportverein von 1896, in dem der Hannoversche FC von 1896 sich mit dem Verein BV Hannovera 1898 fusionierte.', 'Model_Google_Zwei', NULL),
('3', 'Spiel gegen Tottenham Hotspurs', '1914', NULL, 'Ein Highlight - das Spiel gegen Tottenham Hotspurs mit über 10.000 Zuschauern an der Radrennbahn.', 'Model_Google_Drei', NULL),
('4', 'Fußball nach dem Ersten Weltkrieg', '1919', NULL, 'Wiederaufnahme von internationalen Kontakten nach dem ersten Weltkrieg, Testspiele in Schweden und Hannover gegen IFK Malmö.', 'Model_Google', NULL),
('5', 'Die Anfrage von Hindenburg', '1919', NULL, 'Nach dem Ersten fragte der Generalfeldmarschall Paul von Hindenburg in einem Brief das Amt als Ehrenpräsident, welches er letztlich auch eerhalten hat.', 'Model_Google', NULL),
('6', 'Bau des neuen Vereinszentrums', '1931', NULL, 'Der Bau des neuen Vereinsheims am Misburger Damm wird gestartet.', NULL, NULL),
('7', 'Deutschlandweite Bekanntheit', '1932', 'Hannover 96 wurde in den 1930er Jahren deutschlandweit bekannt, und Robert Fuchs wurde der erste hauptberufliche Trainer, der 16 Jahre lang die Mannschaft betreute.', 'In Hannover spielte die Mannschaft stets eine große Rolle, deutschlandweit bekannt wurde sie allerdings erst in den 1930er Jahren. Infolgedessen wurde Robert Fuchs erstmals als ein hauptberuflicher Trainer für die Fußballmannschaft beschäftigt. Dieser wurde mit Unterbrechung 16 Jahre lang Trainer bei Hannover 96.', NULL, NULL);
